#define  BASEADDR_TAG    0x00
#define  BASEADDR_SPORT  0x04
#define  BASEADDR_DPORT  0x04
#define  BASEADDR_QNUM   0x04
#define  BASEADDR_OPC    0x05
#define  BASEADDR_FLAG   0x06
#define  BASEADDR_PROI   0x07
#define  BASEADDR_TAB    0x08
#define  BASEADDR_PRED   0xa
#define  BASEADDR_PCLUST 0xc
#define  BASEADDR_WCLUST 0x2c
#define  BASEADDR_PLOAD  0x3e